ignore:
  - svc-position/src/main/java/com/beancounter/position/PositionBoot.*
  - svc-data/src/main/java/com/beancounter/marketdata/MarketDataBoot.*
  - svc-event/src/main/java/com/beancounter/event/EventBoot.*
  - jar-shell/src/main/java/com/beancounter/shell/ShellRunner.*
  - jar-shell/src/main/java/com/beancounter/shell/google/GoogleAuthConfig.*
  - jar-shell/src/main/java/com/beancounter/shell/google/SheetIngester.*
  - jar-shell/src/main/java/com/beancounter/shell/google/GoogleTransport.*