logging:
  level:
    org.springframework: error
    org.spring: error
    com.google: error
    com.beancounter: debug

com:
  beancounter:
    exchanges:
      aliases:
        ASX: AX
        NYS: NYSE
