server:
  port: 9510
  servlet:
    context-path: '/api'

#management:
#  server:
#    port: 9511
#  endpoint:
#    health.show-details: always
#  endpoints:
#    web:
#      exposure.include: '*'
#      base-path: "/"

logging:
  level:
    com:
      netfix: ERROR
      beancounter: DEBUG
    org:
      springframework:
        test: trace

spring:
  application:
    name: bc-marketData
  cache:
    cache-names: asset.prices

beancounter:
  baseCcy: US

  currencies:
    - code: "GBP"
      id: "GB"
      name: "Pound"
      symbol: "￡"

    - code: USD
      id: US
      name: Dollar
      symbol: $

    - code: NZD
      id: NZ
      name: Dollar
      symbol: $

    - id: AU
      code: AUD
      name: Dollar
      symbol: $

    - id: EU
      code: EUR
      name: Euro
      symbol: €

    - id: SG
      code: SGD
      name: Dollar
      symbol: $

  markets:
    - code: MOCK
      timezoneId: UTC

    - code: NASDAQ
      timezoneId: US/Eastern
      currencyId: US

    - code: NYSE
      timezoneId: US/Eastern
      currencyId: US

    - code: AMEX
      timezoneId: US/Eastern
      currencyId: US

    - code: ASX
      timezoneId: Australia/Sydney
      currencyId: AU
      aliases:
        WTD: AX

    - code: NZX
      timezoneId: Pacific/Auckland
      currencyId: NZ
      aliases:
        WTD: NZ
        ALPHA: NZ

    - code: SGX
      currencyId: SG
      timezoneId: Asia/Singapore


  marketdata:
    provider:
      MOCK:
        markets: MOCK

      ALPHA:
        url: https://www.alphavantage.co
        batchSize: 1
        markets:

      WTD:
        url: https://www.worldtradingdata.com
        batchSize: 2
        markets: NASDAQ,AMEX,NYSE,NZX,ASX


