server:
  port: 9510
  servlet:
    context-path: '/api'

management:
  server:
    port: 9511
  endpoint:
    health.show-details: always
  endpoints:
    web:
      exposure.include: '*'
      base-path: "/"

logging:
  level:
    com:
      netfix: ERROR
      beancounter: DEBUG
    org:
      springframework:
        test: trace

spring:
  application:
    name: bc-marketData
  cache:
    cache-names: asset.prices

beancounter:
  baseCcy: US

  currencies:
    GB:
      code: GBP
      name: Pound
      symbol: ￡

    US:
      code: USD
      name: Dollar
      symbol: $

    NZ:
      code: NZD
      name: Dollar
      symbol: $

    AU:
      code: AUD
      name: Dollar
      symbol: $

    EU:
      code: EUR
      name: Euro
      symbol: €

    SG:
      code: SGD
      name: Dollar
      symbol: $

  markets:
    MOCK:
      timezone: UTC

    NASDAQ:
      timezone: US/Eastern
      currencyId: US
      aliases:
        WTD:
        ALPHA:

    NYSE:
      timezone: US/Eastern
      currencyId: US
      aliases:
        WTD:
        ALPHA:

    AMEX:
      timezone: US/Eastern
      currencyId: US
      aliases:
        WTD:
        ALPHA:

    ASX:
      timezone: Australia/Sydney
      currencyId: AU
      aliases:
        WTD: AX

    NZX:
      timezone: Pacific/Auckland
      currencyId: NZ
      aliases:
        WTD: NZ

    SGX:
      currencyId: SG
      timezone: Asia/Singapore


  marketdata:
    provider:
      MOCK:
        markets: MOCK

      ALPHA:
        url: https://www.alphavantage.co
        batchSize: 1
        markets:

      WTD:
        url: https://www.worldtradingdata.com
        batchSize: 2
        markets: NASDAQ,AMEX,NYSE,NZX,ASX


