server:
  port: 9510


logging:
  level:

    com:
      netfix: ERROR
      beancounter: DEBUG
    org:
      springframework:
        test: trace

spring:
  application:
    name: bc-marketData

beancounter:
  marketdata:
    provider:
      alpha:
        url: https://www.alphavantage.co
    
      worldTradingData:
        url: https://www.worldtradingdata.com

