server:
  port: 9510


logging:
  level:

    com:
      netfix: ERROR
      beancounter: DEBUG
    org:
      springframework:
        test: trace

spring:
  application:
    name: bc-marketData

beancounter:
  markets:
    MOCK:
      currency: USD
      timezone: UTC

    NASDAQ:
      timezone: US/Eastern
      currency: USD
      aliases:
        WTD:
        ALPHA:

    NYSE:
      timezone: US/Eastern
      currency: USD
      aliases:
        WTD:
        ALPHA:

    AMEX:
      timezone: US/Eastern
      currency: USD
      aliases:
        WTD:
        ALPHA:

    ASX:
      timezone: Australia/Sydney
      currency: AUD
      aliases:
        WTD: AX

    NZX:
      timezone: Pacific/Auckland
      currency: NZD
      aliases:
        WTD: NZ


    SGX:
      currency: SGD
      timezone: Asia/Singapore


  marketdata:
    provider:
      MOCK:
        markets: MOCK

      ALPHA:
        url: https://www.alphavantage.co
        batchSize: 1
        markets:

      WTD:
        url: https://www.worldtradingdata.com
        batchSize: 2
        markets: NASDAQ,AMEX,NYSE,NZX,ASX



