server:
  port: 9510


logging:
  level:
    com:
      netfix: ERROR
    org:
      springframework:
        test: trace
spring:
  application:
    name: bc-marketData

com.beancounter.marketdata.provider.alpha:
  url: https://www.alphavantage.co/