server:
  port: 9510


logging:
  level:

    com:
      netfix: ERROR
      beancounter: DEBUG
    org:
      springframework:
        test: trace

spring:
  application:
    name: bc-marketData

beancounter:
  marketdata:
    provider:
      mock:
        markets: MOCK
        
      alpha:
        url: https://www.alphavantage.co
        batchSize: 1
        markets: ASX
    
      worldTradingData:
        url: https://www.worldtradingdata.com
        batchSize: 2
        markets: NASDAQ,AMEX,NYSE


