spring:
  main:
    banner-mode: "off"
    web-application-type: none
server:
  error:
    include-stacktrace: never

feign:
  hystrix:
    enabled: false

beancounter:
  exchanges:
    aliases:
      NYS: NYSE
      NAS: NASDAQ
      AX: ASX
      NZ: NZX

logging:
  level:
    root: debug
    org.springframework.web.servlet: fatal
    org.springframework: error
    org.springframework.boot.web: info
    org.mortbay: error
    org.spring: error
    com.google: error
    org.apache: error
    com.netflix: error
    org: error
    sun: error
    jdk: error
    javax: error
    io.opencensus: error
    io: error
    com.beancounter: debug
    feign.template: error
    io.github.resilience4j: fatal