version: 2
jobs:

  checkout-code:
    machine:
      enabled: true
    working_directory: '~/beancounter'
    steps:
      - checkout
      - save_cache:
          key: beancounter-src-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/beancounter

  build-common:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/beancounter/jar-common'
    # caches are immutable and will be built once by the common job
    steps:
      - restore_cache:
          key: beancounter-src-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: org-beancounter-v2a-{{ checksum "../build.gradle" }}

      - run:
          command: 'rm -rf ~/.m2/repository/com/beancounter'

      - run:
          command: './gradlew clean build '

      - save_cache:
          paths:
            - ~/.m2
            - ../.gradle
          key: org-beancounter-v2a-{{ checksum "../build.gradle" }}

      - store_test_results:
          path: ./build/test-results/test

      - store_artifacts:
          path: jar-common/build/*.jar


  build-google-docs:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/beancounter/svc-import'
    # caches are immutable and will be built once by the common job
    steps:
      - restore_cache:
          key: beancounter-src-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: org-beancounter-v2a-{{ checksum "../build.gradle" }}


      - run:
          command: './gradlew build'

      - save_cache:
          paths:
            - ~/.m2
            - ../.gradle
          key: org-beancounter-v2a-{{ checksum "../build.gradle" }}

      - store_test_results:
          path: ./build/test-results/test

      - store_artifacts:
          path: svc-import/build/*.jar

  build-md:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/beancounter/svc-md'
    # caches are immutable and will be built once by the common job
    steps:
      - restore_cache:
          key: beancounter-src-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: org-beancounter-v2a-{{ checksum "../build.gradle" }}

      - run:
          command: './gradlew build'

      - save_cache:
          paths:
            - ~/.m2
            - ../.gradle
          key: org-beancounter-v2a-{{ checksum "../build.gradle" }}

      - store_test_results:
          path: ./build/test-results/test

      - store_artifacts:
          path: svc-md/build/*.jar

  build-position:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/beancounter/svc-md'
    # caches are immutable and will be built once by the common job
    steps:
      - restore_cache:
          key: beancounter-src-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: org-beancounter-v2a-{{ checksum "../build.gradle" }}

      - run:
          command: './gradlew build'

      - save_cache:
          paths:
            - ~/
            - ../.gradle
          key: org-beancounter-v2a-{{ checksum "../build.gradle" }}

      - store_test_results:
          path: ./build/test-results/test

      - store_artifacts:
          path: svc-md/build/*.jar



workflows:
  version: 2
  build_and_stage:
    jobs:
      - checkout-code
      - build-common:
          requires:
            - checkout-code
      - build-md:
          requires:
            - build-common
      - build-position:
          requires:
            - build-common
      - build-google-docs:
          requires:
            - build-common
