version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build-app:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "./bc-view/yarn.lock" }}
      - run:
          name: Install Dependencies
          command: cd ./bc-view && pwd && yarn install --frozen-lockfile
      - run:
          name: Test with coverage
          command: cd ./bc-view && yarn test --ci --coverage --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "./reports/junit"
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-cache-{{ checksum "~/project/bc-view/yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./bc-view/node_modules
      - store_test_results:
          path: bc-view/reports/junit
      - store_artifacts:
          path: bc-view/reports/junit

  build-data:
    docker:
      - image: circleci/openjdk:11
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-build-cache-{{ checksum "~/project/jar-common/build.gradle" }}-{{ checksum "~/project/svc-data/build.gradle" }}-{{ checksum "~/project/jar-shell/build.gradle" }}-{{ checksum "~/project/svc-position/build.gradle" }}

      - run: 'pwd'
      - run: './gradlew jar-common:build svc-data:build'
      - run: './gradlew svc-data:publishToMavenLocal'

      - store_test_results:
          path: ~/project/svc-data/build/test-results/test

      - codecov/upload:
          file: ~/project/svc-data/build/reports/jacoco/test/*.xml

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-build-cache-{{ checksum "~/project/jar-common/build.gradle" }}-{{ checksum "~/project/svc-data/build.gradle" }}-{{ checksum "~/project/jar-shell/build.gradle" }}-{{ checksum "~/project/svc-position/build.gradle" }}

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
            - ~/project

          key: v1-sha-cache-{{ .Environment.CIRCLE_SHA1 }}

      - store_artifacts:
          path: ~/project/svc-data/build/libs

      - store_artifacts:
          path: ~/project/jar-common/build/libs

  build-shell:
    docker:
      - image: circleci/openjdk:11
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"

    steps:
      - add_ssh_keys:
          fingerprints:
            - "3c:d5:17:fb:41:7c:f2:b1:fe:cd:e4:75:99:34:2e:e2"
      - restore_cache:
          keys:
            - v1-sha-cache-{{ .Environment.CIRCLE_SHA1 }}

      - run: './gradlew jar-shell:build'

      - store_test_results:
          path: ~/project/jar-shell/build/test-results/test

      - codecov/upload:
          file: ~/project/jar-shell/build/reports/jacoco/test/*.xml

      - store_artifacts:
          path: ~/project/jar-shell/build/libs

  build-position:
    docker:
      - image: circleci/openjdk:11
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
      - add_ssh_keys:
          fingerprints:
            - "3c:d5:17:fb:41:7c:f2:b1:fe:cd:e4:75:99:34:2e:e2"

      - restore_cache:
          keys:
            - v1-sha-cache-{{ .Environment.CIRCLE_SHA1 }}

      - run: './gradlew svc-position:build --info'

      - store_test_results:
          path: ~/project/svc-position/build/test-results/test

      - codecov/upload:
          file: ~/project/svc-position/build/reports/jacoco/test/*.xml

      - store_artifacts:
          path: ~/project/svc-position/build/libs

workflows:
  version: 2
  build_and_stage:
    jobs:
      - build-app
      - build-data
      - build-shell:
          requires:
            - build-data
      - build-position:
          requires:
            - build-data
