version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
#  checkout-code:
#    machine:
#      enabled: true
#    steps:
#      - checkout
#      - save_cache:
#          key: org-bc-common-{{ .Environment.CIRCLE_SHA1 }}
#          paths:
#            - ~/beancounter

  build-common:
    docker:
      - image: circleci/openjdk:11
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"

    # Restore cached artifacts from a builds
    steps:
      - checkout
      - restore_cache:
          keys:
            - org-beancounter-build-cache-{{ checksum "~/project/jar-common/build.gradle" }}-{{ checksum "~/project/svc-md/build.gradle" }}-{{ checksum "~/project/svc-ingest/build.gradle" }}-{{ checksum "~/project/svc-position/build.gradle" }}
      - run: 'rm -rf ~/.m2/repository/com/beancounter'
      - run: 'rm -rf ~/.m2/repository/beancounter'
      - run: 'pwd'
      - run: 'cd ~/project/jar-common && ./gradlew clean build'
      - run: 'cd ~/project/svc-md && ./gradlew publishStubsPublicationToMavenLocal'

      # Save the environment for this build run with it's dependencies in-place
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
            - ~/project
          key: org-beancounter-build-artifacts-{{ .Environment.CIRCLE_SHA1 }}

      - store_test_results:
          path: ~/project/jar-common/build/test-results/test

      - codecov/upload:
          file: ~/project/jar-common/build/reports/jacoco/test/*.xml

      - store_artifacts:
          path: ~/project/jar-common/build/libs

  build-md:
    docker:
      - image: circleci/openjdk:11
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    # caches are immutable and will be built once by the common job
    steps:
      - restore_cache:
          keys:
            - org-beancounter-build-artifacts-{{ .Environment.CIRCLE_SHA1 }}

      - run: 'pwd'
      - run: 'cd ~/project/svc-md && ./gradlew build'

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
          key: org-beancounter-build-cache-{{ checksum "~/project/jar-common/build.gradle" }}-{{ checksum "~/project/svc-md/build.gradle" }}-{{ checksum "~/project/svc-ingest/build.gradle" }}-{{ checksum "~/project/svc-position/build.gradle" }}

      - store_test_results:
          path: ~/project/svc-md/build/test-results/test

      - codecov/upload:
          file: ~/project/svc-md/build/reports/jacoco/test/*.xml

      - store_artifacts:
          path: ~/project/svc-md/build/libs

  build-ingest:
    docker:
      - image: circleci/openjdk:11
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    steps:
      - restore_cache:
          keys:
            - org-beancounter-build-artifacts-{{ .Environment.CIRCLE_SHA1 }}

      - run: 'cd ~/project/svc-ingest && ./gradlew build'

      - store_test_results:
          path: ~/project/svc-ingest/build/test-results/test

      - codecov/upload:
          file: ~/project/svc-ingest/build/reports/jacoco/test/*.xml

      - store_artifacts:
          path: ~/project/svc-ingest/build/libs

  build-position:
    docker:
      - image: circleci/openjdk:11
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"

    steps:
      - restore_cache:
          keys:
            - org-beancounter-build-artifacts-{{ .Environment.CIRCLE_SHA1 }}

      - run: 'cd ~/project/svc-position && ./gradlew build'

      - store_test_results:
          path: ~/project/svc-position/build/test-results/test

      - codecov/upload:
          file: ~/project/svc-position/build/reports/jacoco/test/*.xml

      - store_artifacts:
          path: ~/project/svc-position/build/libs

workflows:
  version: 2
  build_and_stage:
    jobs:
      - build-common
      - build-md:
          requires:
            - build-common
      - build-position:
          requires:
            - build-md
      - build-ingest:
          requires:
            - build-md
