version: '3.5'
services:

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bc
    volumes:
      - pg-data:/var/lib/backup/data

  keycloak:
    # https://ordina-jworks.github.io/security/2019/08/22/Securing-Web-Applications-With-Keycloak.htm
    image: jboss/keycloak
    container_name: keycloak
    #    entrypoint: /opt/jboss/tools/docker-entrypoint.sh -Dkeycloak.profile.feature.token_exchange=enabled
    expose:
      - 8080
    ports:
      - 9620:8080
    environment:
      # https://ultimatesecurity.pro/post/okta-oidc/
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: beancounter
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: bc
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: password
    depends_on:
      - postgres

  data:
    image: bc/svc-data
    container_name: data
    expose:
      - 9510
    # Ports should be published if you are running local:bc-view against this stack
    ports:
      - 9610:9510
    environment:
      SERVER_PORT: 9510
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bc
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      # https://docs.docker.com/compose/environment-variables/
      BEANCOUNTER_MARKETDATA_PROVIDER_WTD_KEY: ${WTD}
      AUTH_URI: "http://keycloak:8080"
      AUTH_REALM: "bc-dev"
    links:
      - postgres

  position:
    image: bc/svc-position
    container_name: position
    expose:
      - 9500
    # Publish this if you are running local:bc-view against docker services
    ports:
      - 9600:9500

    environment:
      SERVER_PORT: 9500
      MARKETDATA_URL: "http://data:9510/api"
      MANAGEMENT_SERVER_PORT: 9621
      AUTH_URI: "http://keycloak:8080"
      AUTH_REALM: "bc-dev"
    depends_on:
      - data

  app:
    image: bc/app
    ports:
      - 4000:3000

    container_name: app
    environment:
      SVC_POSITION: "http://position:9500"
      SVC_DATA: "http://data:9600"
      RAZZLE_PUBLIC_DIR: "http://localhost:4000"
    depends_on:
      - position

volumes:
  pg-data:
