server:
  port: 9500
  servlet:
    context-path: '/api'

management:
  server:
    port: 9501
  endpoint:
    health.show-details: always
  endpoints:
    web:
      exposure.include: '*'

marketdata:
  url: "http://localhost:9510/api"

auth:
  uri: "http://keycloak:9620/auth"
  realm: "bc-dev"

spring:
  application:
    name: bc-positionKeeper
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${auth.uri}/realms/${auth.realm}/protocol/openid-connect/certs"

endpoints:
  default.web.enabled: true

logging:
  level:
    root: debug
    javax: error
    sun: error
    io: error
    netflix: error
    jdk: error
    feign: fatal
    com:
      netfix: error
      beancounter: debug
      zaxxer: error
    org:
      springframework: error
      hibernate: error
      apache: error
      postgres: error

feign:
  client:
    config:
      default:
        # Loooong because of API limits with data providers
        readTimeout: 50000
        errorDecoder: com.beancounter.common.exception.SpringFeignDecoder

    # http://localhost:9500/actuator/circuitbreaker-events/marketdata

resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 3
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      waitDurationInOpenState: 5s
      registerHealthIndicator: true
      recordFailurePredicate: com.beancounter.common.exception.RecordFailurePredicate
