server:
  port: 9500
  servlet:
    context-path: '/api'

management:
  server:
    port: 9501
  endpoint:
    health.show-details: always
  endpoints:
    web:
      exposure.include: '*'
#      base-path: "/"

marketdata:
    name: marketdata
    url: "http://localhost:9510/api"

spring:
  application:
    name: bc-positionKeeper



endpoints:
  default.web.enabled: true

logging:
  level:
    root: debug
    org.springframework.web.servlet: fatal
    org.springframework: error
    org.springframework.boot.web: info
    org.mortbay: error
    org.spring: error
    com.google: error
    org.apache: error
    com.netflix: error
    org: error
    sun: error
    jdk: error
    javax: error
    io.opencensus: error
    io: error
    com.beancounter: debug
    feign.template: error
    io.github.resilience4j: fatal
feign:
  client:
    config:
      default:
        errorDecoder: com.beancounter.common.exception.SpringFeignDecoder

    # http://localhost:9500/actuator/circuitbreaker-events/marketdata

resilience4j.circuitbreaker:
  backends:
    marketdata:
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitInterval: 3000
      failureRateThreshold: 2
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
      recordFailurePredicate: com.beancounter.common.exception.RecordFailurePredicate
#      recordExceptions:
#        - org.springframework.web.client.HttpServerErrorException
#      ignoreExceptions:
#        - org.springframework.web.client.HttpClientErrorException