server:
  port: 9500
  servlet:
    context-path: '/api'

management:
  server:
    port: 9501
  endpoint:
    health.show-details: always
  endpoints:
    web:
      exposure.include: '*'

marketdata:
  url: "http://localhost:9510/api"

auth:
  uri: "http://keycloak:9620"
  realm: "bc-dev"

spring:
  application:
    name: bc-positionKeeper
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${auth.uri}/auth/realms/${auth.realm}/protocol/openid-connect/certs"

endpoints:
  default.web.enabled: true

logging:
  level:
    root: debug
    org.springframework.web.servlet: fatal
    org.springframework: info
    org.springframework.boot.web: info
    org.mortbay: error
    org.spring: error
    com.google: error
    org.apache: error
    com.netflix: error
    org: error
    sun: error
    jdk: error
    javax: error
    io.opencensus: error
    io: error
    com.beancounter: debug
    feign.template: error
    io.github.resilience4j: fatal
feign:
  client:
    config:
      default:
        errorDecoder: com.beancounter.common.exception.SpringFeignDecoder

    # http://localhost:9500/actuator/circuitbreaker-events/marketdata

resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 3
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      waitDurationInOpenState: 5s
      registerHealthIndicator: true
      recordFailurePredicate: com.beancounter.common.exception.RecordFailurePredicate
