server:
  port: 9510
  servlet:
    context-path: '/api'

management:
  server:
    port: 9511
  endpoint:
    health.show-details: always
  endpoints:
    web:
      exposure.include: '*'
      base-path: "/"

logging:
  level:
    com:
      netfix: ERROR
      beancounter: DEBUG
    org:
      springframework: error

spring:
  application:
    name: bc-marketData
  cache:
    cache-names: asset.prices
  jpa:
    open-in-view: false
    generate-ddl: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  h2:
    console:
      enabled: true
      path: /h2

beancounter:
  baseCode: "USD"

  currencies:
    - code: "GBP"
      name: "Pound"
      symbol: "￡"

    - code: USD
      name: Dollar
      symbol: $

    - code: NZD
      name: Dollar
      symbol: $

    - code: AUD
      name: Dollar
      symbol: $

    - code: EUR
      name: Euro
      symbol: €

    - code: SGD
      name: Dollar
      symbol: $

  markets:
    - code: MOCK
      id: MOCK
      timezoneId: UTC

    - code: NASDAQ
      id: NASDAQ
      timezoneId: US/Eastern
      currencyCode: USD

    - code: NYSE
      id: NYSE
      timezoneId: US/Eastern
      currencyCode: USD

    - code: AMEX
      id: AMEX
      timezoneId: US/Eastern
      currencyCode: USD

    - code: ASX
      id: ASX
      timezoneId: Australia/Sydney
      currencyCode: AUD
      aliases:
        WTD: AX

    - code: NZX
      id: NZX
      timezoneId: Pacific/Auckland
      currencyCode: NZD
      aliases:
        WTD: NZ
        ALPHA: NZ

    - code: SGX
      id: SGX
      currencyCode: SGD
      timezoneId: Asia/Singapore


  marketdata:
    provider:
      MOCK:
        markets: MOCK

      ALPHA:
        url: https://www.alphavantage.co
        batchSize: 1
        markets:

      WTD:
        url: https://www.worldtradingdata.com
        batchSize: 2
        markets: NASDAQ,AMEX,NYSE,NZX,ASX


