server:
  port: 9510
  servlet:
    context-path: '/api'

management:
  server:
    port: 9511
  endpoint:
    health.show-details: always
  endpoints:
    web:
      exposure.include: '*'
      base-path: "/"

logging:
  level:
    root: debug
    javax: error
    sun: error
    netflix: error
    jdk: error
    io:
      github:
        resilience4j: error
    feign: error
    com:
      netfix: error
      beancounter: debug
      zaxxer: error
    org:
      springframework: error
      springframework.scheduling: debug
      hibernate: error
      apache: error
      postgres: error
      postgresql: error

auth:
  uri: "http://keycloak:9620/auth"
  realm: "bc-dev"

spring:
  application:
    name: bc-data
  cache:
    cache-names: asset.prices, asset.search, fx.rates, providers, asset.ext, currency.code, currency.all
  jpa:
    open-in-view: false
    generate-ddl: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${auth.uri}/realms/${auth.realm}/protocol/openid-connect/certs"
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: bc-data
#      properties:
#        spring.json.trusted.packages: com.beancounter.common.input
#        spring.json.use.type.headers: false
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer



kafka:
  enabled: false

beancounter:
  currency:
    base: "USD"
    values:
      - code: GBP
        name: Pound
        symbol: ￡

      - code: USD
        name: Dollar
        symbol: $

      - code: NZD
        name: Dollar
        symbol: $

      - code: AUD
        name: Dollar
        symbol: $

      - code: EUR
        name: Euro
        symbol: €

      - code: SGD
        name: Dollar
        symbol: $
  # Default asset enricher - FIGI/ALPHA/MOCK - can be set on a per market basis
  enricher: ALPHA
  market:
    values:
      - code: MOCK
        id: MOCK
        timezoneId: UTC
        enricher: MOCK

      - code: NASDAQ
        id: NASDAQ
        timezoneId: US/Eastern
        currencyId: USD
        aliases:
          SHARESIGHT: NAS
          FIGI: US

      - code: NYSE
        id: NYSE
        timezoneId: US/Eastern
        currencyId: USD
        aliases:
          SHARESIGHT: NYS
          FIGI: US

      - code: AMEX
        id: AMEX
        timezoneId: US/Eastern
        currencyId: USD
        aliases:
          FIGI: US

      - code: ASX
        id: ASX
        timezoneId: Australia/Sydney
        currencyId: AUD
        aliases:
          WTD: AX
          FIGI: AU

      - code: NZX
        id: NZX
        timezoneId: Pacific/Auckland
        currencyId: NZD
        aliases:
          WTD: NZ
          ALPHA: NZ
          FIGI: NZ

      - code: SGX
        id: SGX
        currencyId: SGD
        timezoneId: Asia/Singapore
        aliases:
          FIGI: SG

      - code: LSE
        id: LSE
        currencyId: GBP
        timezoneId: Europe/London
        aliases:
          FIGI: GB

      - code: LON
        # UK Mutual Funds
        id: LON
        currencyId: GBP
        timezoneId: Europe/London
        multiplier: .01
    providers:
      # ToDo: default provider
      MOCK:
        markets: MOCK

      ALPHA:
        url: https://www.alphavantage.co
        batchSize: 1
        markets: NASDAQ,AMEX,NYSE,ASX,LON

      WTD:
        url: https://www.worldtradingdata.com
        batchSize: 2
        markets: NZX


resilience4j.ratelimiter:
  instances:
    figi:
      registerHealthIndicator: false
      limitForPeriod: 60
      limitRefreshPeriod: 65s
      timeoutDuration: 80s
      eventConsumerBufferSize: 200
    alphaVantage:
      registerHealthIndicator: false
      limitForPeriod: 25
      limitRefreshPeriod: 65s
      timeoutDuration: 80s
      eventConsumerBufferSize: 200

resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 3
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      waitDurationInOpenState: 5s
      registerHealthIndicator: true
      recordFailurePredicate: com.beancounter.common.exception.RecordFailurePredicate

