server:
  port: 9510
  servlet:
    context-path: '/api'

management:
  server:
    port: 9511
  endpoint:
    health.show-details: always
  endpoints:
    web:
      exposure.include: '*'
      base-path: "/"

logging:
  level:
    root: debug
    javax: error
    sun: error
    io: error
    com:
      netfix: error
      beancounter: debug
      zaxxer: error
    org:
      springframework: error
      hibernate: error
      apache: error
      postgres: error
      postgresql: error

auth:
  uri: "http://keycloak:9620/auth"
  realm: "bc-dev"

spring:
  application:
    name: bc-marketData
  cache:
    cache-names: asset.prices, ecb.rates
  jpa:
    open-in-view: false
    generate-ddl: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${auth.uri}/realms/${auth.realm}/protocol/openid-connect/certs"

beancounter:
  baseCode: "USD"

  currencies:
    - code: GBP
      name: Pound
      symbol: ￡

    - code: USD
      name: Dollar
      symbol: $

    - code: NZD
      name: Dollar
      symbol: $

    - code: AUD
      name: Dollar
      symbol: $

    - code: EUR
      name: Euro
      symbol: €

    - code: SGD
      name: Dollar
      symbol: $

  markets:
    - code: MOCK
      id: MOCK
      timezoneId: UTC

    - code: NASDAQ
      id: NASDAQ
      timezoneId: US/Eastern
      currencyId: USD

    - code: NYSE
      id: NYSE
      timezoneId: US/Eastern
      currencyId: USD

    - code: AMEX
      id: AMEX
      timezoneId: US/Eastern
      currencyId: USD

    - code: ASX
      id: ASX
      timezoneId: Australia/Sydney
      currencyId: AUD
      aliases:
        WTD: AX

    - code: NZX
      id: NZX
      timezoneId: Pacific/Auckland
      currencyId: NZD
      aliases:
        WTD: NZ
        ALPHA: NZ

    - code: SGX
      id: SGX
      currencyId: SGD
      timezoneId: Asia/Singapore

    - code: LSE
      id: LSE
      currencyId: GBP
      timezoneId: Europe/London

  marketdata:
    provider:
      MOCK:
        markets: MOCK

      ALPHA:
        url: https://www.alphavantage.co
        batchSize: 1
        markets:

      WTD:
        url: https://www.worldtradingdata.com
        batchSize: 2
        markets: NASDAQ,AMEX,NYSE,NZX,ASX


